### ISSUE TITLE
ValueError: Negative dimension size caused by subtracting 32 from 24 for 'average_pooling2d_1/AvgPool' (op: 'AvgPool') with input shapes: [1,24,24,2048]

### ISSUE THREAD

**Issue by daxiaoshu** [bonlime/keras-deeplab-v3-plus#21]

**Comment by daxiaoshu** [comment]
but when data_shape=(512,512,3) ,have no problem

**Comment by bonlime** [comment]
What output stride and backbone do you use?

**Comment by daxiaoshu** [comment]
output stride =16 @bonlime

**Comment by daxiaoshu** [comment]
output stride=16 ,  backbone  is xecption @bonlime

**Comment by bonlime** [comment]
@daxiaoshu 
I tried to use:
`model = Deeplabv3(weights=None, input_shape=(384, 384, 3), classes=15, backbone='xception', OS=16)`
on images with shape (384,384,3) and it works fine for me. Maybe problem is in some other place  
This error happens to you because `int(np.ceil(input_shape[0] / OS))` in pool_size is bigger than 24, which don't happen in my setting

**Comment by CalinTimbusLucian** [comment]
I also have this issue, no matter how much I change the input shape or other parameters :(

**Comment by CalinTimbusLucian** [comment]
NOTE FOR OTHERS: It may be the case that this error happens; By restarting the kernel, I was able to solve it.

**Comment by bonlime** [comment]
@CalinTimbusLucian I can't help you because I can't reproduce this error. Give me the steps to get it and I will try to fix

**Comment by CalinTimbusLucian** [comment]
bonlime thanks for the prompt response. I restarted the kernel in Spyder and then it worked(don't ask me why, I have absolutely no idea) 👍
