### ISSUE TITLE
How to get the same image inference result as you listed?

### ISSUE THREAD

**Issue by eewindfly** [bonlime/keras-deeplab-v3-plus#94]
I simply follow the inference guide as you mentioned on README.
And it did work, however, the image inference quality seems a little bit difference with your result.

Here is the code I run for inference.
```
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

from model import Deeplabv3

# Generates labels using most basic setup.  Supports various image sizes.  Returns image labels in same format
# as original image.  Normalization matches MobileNetV2

trained_image_width=512
mean_subtraction_value=127.5
image = np.array(Image.open('imgs/image1.jpg'))

# resize to max dimension of images from training dataset
w, h, _ = image.shape
ratio = float(trained_image_width) / np.max([w, h])
resized_image = np.array(Image.fromarray(image.astype('uint8')).resize((int(ratio * h), int(ratio * w))))

# apply normalization for trained dataset images
resized_image = (resized_image / mean_subtraction_value) - 1.

# pad array to square image to match training images
pad_x = int(trained_image_width - resized_image.shape[0])
pad_y = int(trained_image_width - resized_image.shape[1])
resized_image = np.pad(resized_image, ((0, pad_x), (0, pad_y), (0, 0)), mode='constant')

# make prediction
deeplab_model = Deeplabv3(backbone="mobilenetv2", OS=8)
res = deeplab_model.predict(np.expand_dims(resized_image, 0))
labels = np.argmax(res.squeeze(), -1)

# remove padding and resize back to original image
if pad_x > 0:
    labels = labels[:-pad_x]
if pad_y > 0:
    labels = labels[:, :-pad_y]
labels = np.array(Image.fromarray(labels.astype('uint8')).resize((h, w)))

plt.imshow(labels)
plt.waitforbuttonpress()
```
Then, I got
![image](https://user-images.githubusercontent.com/7156964/56951882-83e4e680-6b6b-11e9-8acc-e501bcc6535b.png)

I am guessing that maybe backbond is the reason for the bad result,
so I modify the backbond to xception, then got
![image](https://user-images.githubusercontent.com/7156964/56952052-ea6a0480-6b6b-11e9-9b42-616c70a4d30e.png)

As you can see, both of them are not the same with the original result as you claim in "imgs/my_seg_results1_OS8.png"
![image](https://user-images.githubusercontent.com/7156964/56952144-2a30ec00-6b6c-11e9-91e4-e006b28c0df5.png)

Could you kindly tell me what params you used to get the great result?
Thanks a lot.

**Comment by bonlime** [comment]
Hi. The code I used to create the images in README was lost a long time ago but i used the `weights='pascal_voc', backbone='xception', OS=8`. I tried running your example on my machine with  this parameters got the result identical to yours. But then I tried using cv2 for resize instead of PIL:
```
#image = np.array(Image.open('imgs/image1.jpg'))
image = plt.imread("imgs/image1.jpg")
...
resized_image = cv2.resize(img,(int(ratio*h),int(ratio*w)))
#resized_image = np.array(Image.fromarray(image.astype('uint8')).resize((int(ratio * h), int(ratio * w))))
```
and got this: 
![image](https://user-images.githubusercontent.com/14337581/56997212-a9262480-6b6c-11e9-950b-174ca44b637a.png)
which is a little closer to the one in README. Looks like even such small details may affect the final resuly but the quality drops insignificantlly. Maybe something in TF resize also was changed in the past year, which may be the reason why images are not pixel to pixel identical. 
all in all the results are still great :)
